/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumProjectStatus } from "./EnumProjectStatus";

import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";

import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { FinancialRecordCreateNestedManyWithoutProjectsInput } from "./FinancialRecordCreateNestedManyWithoutProjectsInput";
import { NotificationCreateNestedManyWithoutProjectsInput } from "./NotificationCreateNestedManyWithoutProjectsInput";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumProjectStatus,
  })
  @IsEnum(EnumProjectStatus)
  @IsOptional()
  @Field(() => EnumProjectStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  budget?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  paymentDetails?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FinancialRecordCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => FinancialRecordCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => FinancialRecordCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  financialRecords?: FinancialRecordCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutProjectsInput;
}

export { ProjectCreateInput as ProjectCreateInput };
