/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumProjectStatus } from "./EnumProjectStatus";

import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";

import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { FinancialRecordUpdateManyWithoutProjectsInput } from "./FinancialRecordUpdateManyWithoutProjectsInput";
import { NotificationUpdateManyWithoutProjectsInput } from "./NotificationUpdateManyWithoutProjectsInput";

@InputType()
class ProjectUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumProjectStatus,
  })
  @IsEnum(EnumProjectStatus)
  @IsOptional()
  @Field(() => EnumProjectStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  budget?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  paymentDetails?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FinancialRecordUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => FinancialRecordUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => FinancialRecordUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  financialRecords?: FinancialRecordUpdateManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutProjectsInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutProjectsInput;
}

export { ProjectUpdateInput as ProjectUpdateInput };
